# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/progressbar/all/progressbar.rbi
#
# progressbar-1.11.0

class ProgressBar
  def self.create(*args); end
end
